services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - bibular

  app_server:
    container_name: app_server
    build: .
    image: bibular-server
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    networks:
      - bibular

networks:
  bibular:
    driver: bridge